name: affise_attribution_lib
description: Affise Attribution Flutter plugin. Use to collect application usage statistics. You can read more about Affise at affise.com.
version: 1.7.5
homepage: https://affise.com/
repository: https://github.com/affise/affise-mmp-sdk-flutter
issue_tracker: https://github.com/affise/affise-mmp-sdk-flutter/issues
documentation: https://github.com/affise/affise-mmp-sdk-flutter

platforms:
  android:
  ios:

topics:
  - mobile
  - metrics

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  lints: ^6.1.0

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.affise.attribution.affise_attribution_lib
        pluginClass: AffiseAttributionLibPlugin
      ios:
        pluginClass: AffiseAttributionLibPlugin
