import 'package:affise_attribution_lib/affise.dart';

import 'events_factory.dart';

class SimpleEventsFactory implements EventsFactory {
  @override
  List<Event> createEvents() {
    return [
      AchieveLevelEvent(),
      AddPaymentInfoEvent(),
      AddToCartEvent(),
      AddToWishlistEvent(),
      AdRevenueEvent(),
      ClickAdvEvent(),
      CompleteRegistrationEvent(),
      CompleteStreamEvent(),
      CompleteTrialEvent(),
      CompleteTutorialEvent(),
      ContactEvent(),
      ContentItemsViewEvent(),
      CustomId01Event(),
      CustomId02Event(),
      CustomId03Event(),
      CustomId04Event(),
      CustomId05Event(),
      CustomId06Event(),
      CustomId07Event(),
      CustomId08Event(),
      CustomId09Event(),
      CustomId10Event(),
      CustomizeProductEvent(),
      DeepLinkedEvent(),
      DonateEvent(),
      FindLocationEvent(),
      InitiateCheckoutEvent(),
      InitiatePurchaseEvent(),
      InitiateStreamEvent(),
      InviteEvent(),
      LastAttributedTouchEvent(),
      LeadEvent(),
      ListViewEvent(),
      LoginEvent(),
      OpenedFromPushNotificationEvent(),
      OrderEvent(),
      OrderItemAddedEvent(),
      OrderItemRemoveEvent(),
      OrderCancelEvent(),
      OrderReturnRequestCancelEvent(),
      OrderReturnRequestEvent(),
      PurchaseEvent(),
      RateEvent(),
      ReEngageEvent(),
      ReserveEvent(),
      SalesEvent(),
      ScheduleEvent(),
      SearchEvent(),
      ShareEvent(),
      SpendCreditsEvent(),
      StartRegistrationEvent(),
      StartTrialEvent(),
      StartTutorialEvent(),
      SubmitApplicationEvent(),
      SubscribeEvent(),
      TravelBookingEvent(),
      UnlockAchievementEvent(),
      UnsubscribeEvent(),
      UpdateEvent(),
      ViewAdvEvent(),
      ViewCartEvent(),
      ViewContentEvent(),
      ViewItemEvent(),
      ViewItemsEvent(),
      InitialSubscriptionEvent(data: {}),
      InitialTrialEvent(data: {}),
      InitialOfferEvent(data: {}),
      FailedTrialEvent(data: {}),
      FailedOfferiseEvent(data: {}),
      FailedSubscriptionEvent(data: {}),
      FailedTrialFromRetryEvent(data: {}),
      FailedOfferFromRetryEvent(data: {}),
      FailedSubscriptionFromRetryEvent(data: {}),
      TrialInRetryEvent(data: {}),
      OfferInRetryEvent(data: {}),
      SubscriptionInRetryEvent(data: {}),
      ConvertedTrialEvent(data: {}),
      ConvertedOfferEvent(data: {}),
      ReactivatedSubscriptionEvent(data: {}),
      RenewedSubscriptionEvent(data: {}),
      ConvertedTrialFromRetryEvent(data: {}),
      ConvertedOfferFromRetryEvent(data: {}),
      RenewedSubscriptionFromRetryEvent(data: {}),
      UnsubscriptionEvent(data: {}),
    ];
  }
}
