name: 🏗️ Publish
run-name: Publish ${{ github.ref_name }}

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    name: Publish Flutter Library
    permissions:
      id-token: write # Required for authentication using OIDC
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Version Tag
        id: version_tag
        run: |
          echo Version: ${GITHUB_REF_NAME}
          echo "VERSION=${GITHUB_REF_NAME}" >> "$GITHUB_OUTPUT"

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4

      # Dependencies
      - name: Install Affise Attribution Lib dependencies
        working-directory: affise_attribution_lib
        run: flutter pub get

      - name: Install Affise Attribution Advertising Module dependencies
        working-directory: affise_attribution_module_advertising
        run: flutter pub get

      # Dry Run
      - name: Publish Affise Attribution Lib - dry run
        working-directory: affise_attribution_lib
        run: flutter pub publish --dry-run

      - name: Publish Affise Attribution Advertising Module - dry run
        working-directory: affise_attribution_module_advertising
        run: flutter pub publish --dry-run 

      # Publish
      - name: Publish Affise Attribution Lib to pub.dev
        working-directory: affise_attribution_lib
        run: flutter pub publish --force

      - name: Publish Affise Attribution Advertising Module to pub.dev
        working-directory: affise_attribution_module_advertising
        run: flutter pub publish --force

      - name: Tg Release failed
        continue-on-error: true
        id: tg_failed
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          disable_web_page_preview: true
          message: |
            🔴 Flutter `${{ steps.version_tag.outputs.VERSION }}` release failed

            [Github Action](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

      - name: Tg Release
        continue-on-error: true
        id: tg_success
        if: ${{ success() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          disable_web_page_preview: true
          message: |
            🟢 Flutter `${{ steps.version_tag.outputs.VERSION }}` release

            [Changelog](https://github.com/${{ github.repository }}/blob/${{ github.ref_name }}/CHANGELOG.md)

      - name: Release
        if: ${{ !contains(github.event.ref, '-') }}
        id: create_release
        continue-on-error: true
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Affise Attribution Flutter Library ${{ github.ref }}
          draft: false
          prerelease: false
